### ISSUE TITLE
Question: How to best automate loading up a blank Gitea with our stack and setup mirroring

### ISSUE THREAD

**Issue by zramsay** [cerc-io/hosting#27]
Context: I can reliably stand up the `package-registry` stack (which maybe isn't a broad enough name) but am not sure what the next step would be to efficiently and reliably "load" all our GH repos, mirrored *from* GH. It's easy enough to do manually :(

Of course, the goal is the reverse the mirror at some point but IMO a good first step is to get S-O to spin up gitea *with all of GH mirrored*; this would also be a great task to assign the membership...use S-O to host a mirror of our stack in gitea. Once we switch, S-O would be configured to run a gitea mirror from the authoritative gitea.

[https://docs.gitea.io/en-us/repo-mirror/](https://docs.gitea.io/en-us/repo-mirror/) --> nothing about automating this

[https://github.com/maxgallup/gitea-migrate](https://github.com/maxgallup/gitea-migrate) --> most recent tool I could find

**Comment by dboreham** [comment]
I think this would be a case of reviewing the GT code, finding the back-end area that implements the migrate button and then seeing if it is wired up to the API. There may be some chatter about this in their issues or Discord.

If it's not API-aware, then next step would be to add that code, or wait for someone else to do it.

**Comment by dboreham** [comment]
We now have a tool to help with this: https://github.com/cerc-io/hosting/blob/main/gitea/migrate-repo.sh

**Comment by zramsay** [comment]
I get "Illegal number of parameters" as a response, after editing the last line to not pipe to jq for the html_url. Investigating further

**Comment by zramsay** [comment]
got it working, had to create a new token that had the `repo` scope. The default token from running the `package-registry` stack had `package and `sudo` scopes ... I guess sudo doesn't mean what I expected to mean 🤷

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/hosting/issues/27
