### ISSUE TITLE
Support automatically available docker functionality

### ISSUE THREAD

**Issue by dboreham** [cerc-io/hosting#31]
Currently because Gitea's act code overrides the execution container's entrypoint, we are not able to initialize the docker deamon transparently. Current workaround is to explicitly start the daemon as a step in each job that uses docker.

This can be fixed in the upstream code by using a command in place of overriding the entrypoint, allowing us to use our own entrypoint script to perform docker start.

In addition, the DOCKER_HOST environment variable needs to end up set correctly.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/hosting/issues/31
