### ISSUE TITLE
Gitea 1.20 breaks actions runner

### ISSUE THREAD

**Issue by dboreham** [cerc-io/hosting#46]
```
OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/workspace/cerc-io/stack-orchestrator") set in config.json failed: no such file or directory: unknown
```

**Comment by dboreham** [comment]
![image](https://github.com/cerc-io/hosting/assets/1649760/66bee688-0617-4a73-a7e4-b47116423b6d)

**Comment by telackey** [comment]
Strangely this worked on my first try using a migrated test repo (https://github.com/telackey/test-gitea-sync):

<img width="1216" alt="Screenshot 2023-06-20 at 3 16 41 PM" src="https://github.com/cerc-io/hosting/assets/1649771/363f53d3-7bf2-4d60-9383-6a86557e348a">

Also interestingly the version is printed differently, even though we seem to be on the same version: 1.20.0+rc0-96-gfeda50632

**Comment by telackey** [comment]
On a related note, I'm having trouble migrating stack-orchestrator to test it.  The migration keeps timing out during the "Migrating Git Data" phase.

**Comment by telackey** [comment]
This is potentially interesting:

```
::debug::GITHUB_WORKSPACE = '/cerc-io/test-gitea-sync'
::debug::qualified repository = 'cerc-io/test-gitea-sync'
```

While your error message has: `/workspace/cerc-io/stack-orchestrator`

**Comment by telackey** [comment]
I "migrated" manually by creating a new Gitea repo and adding it as a remote, then pushing.

It seems to have worked:
<img width="1298" alt="Screenshot 2023-06-20 at 3 31 30 PM" src="https://github.com/cerc-io/hosting/assets/1649771/3e4440e4-b1af-4e9f-b5f5-9f3ee8817a52">

I build all the containers cleanly from scratch, but I did have some existing Gitea config from 1.19.

Should I try again completely clean?

**Comment by dboreham** [comment]
Closing as invalid
