### ISSUE TITLE
Increase length of a Gitea session for a user (cookies?)

### ISSUE THREAD

**Issue by zramsay** [cerc-io/hosting#48]
bit of nit but it's probably my biggest hurdle to using Gitea regularly. 

The length of a "logged in" session is very low. E.g., I can't remember the last time I logged into Github. With Gitea, I have to log in every day. Not really an issue w/o 2FA enabled, but with 2FA it becomes tedious (relative to every other service that prompts 2FA after, eg., 1 week of inactivity, rather than some <24hr amount of time since closing the tab.)

**Comment by dboreham** [comment]
This is set via the `LOGIN_REMEMBER_DAYS` config option, and defaults to 7 days.
I'm going to watch to see how long my cookies last -- my sense is the same as Zach's that they don't last a week.
I doubt we overrode the default config, although I haven't checked that on the server yet.

**Comment by dboreham** [comment]
I think this has been fixed now. I tested by logging into gitea, waiting a few days, then checking if the session was still valid. It was. I did notice however that a Chrome tab in another Chrome window on the same machine, that had been open much longer, did not have a valid session. Not sure how that comes about, but it might explain the problem. Closing for now.
