### ISSUE TITLE
Docker bind mounts don't work inside Gitea runners

### ISSUE THREAD

**Issue by roysc** [cerc-io/hosting#50]
The Gitea runners are using the shared-socket approach to run nested docker containers, which means bind-mounts use the host's filesystem as source. This is incompatible with stack-orchestrator compose files and other components (like statediff file indexing tests), which expect to be able to read and write to local files. A clean workaround for this doesn't look possible.

But with @telackey 's additions to act_runner, it seems that using `docker:dind` for the runners should be feasible, which should solve this problem.

**Comment by roysc** [comment]
I expect this https://git.vdb.to/cerc-io/plugeth-statediff/actions/runs/62/jobs/0 to fail in the [unit test step](https://git.vdb.to/cerc-io/plugeth-statediff/src/commit/ad8583dddd7ad893f48b2c4ea98a3b9ed8dee221/.gitea/workflows/test.yml#L29), once it runs. I will update here once there's a good example.

**Comment by telackey** [comment]
FWIW, David and I discussed some improvements to the act_runner which would remove the step of manually starting dockerd, but we haven't deployed them yet, so this is still necessary at the moment.
